# Generated by Django 2.1.7 on 2019-03-22 19:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('ticker', models.CharField(help_text='Enter the ticker for this transaction', max_length=5, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Enter the quantity for this transaction', validators=[django.core.validators.MinValueValidator(1)])),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttt.TransactionHistory')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this transaction', primary_key=True, serialize=False)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, help_text='Current amount for player', max_digits=11, null=True)),
                ('holdings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ttt.Holdings')),
                ('league', models.ForeignKey(help_text='Select a league for this transaction', on_delete=django.db.models.deletion.CASCADE, to='ttt.League')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['player', 'league'],
            },
        ),
    ]
