# Generated by Django 2.1.7 on 2019-03-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionString', models.CharField(max_length=100)),
                ('LeagueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttt.League')),
            ],
        ),
    ]
