# Generated by Django 2.1.7 on 2019-03-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0002_holdings_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='holdings',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='holdings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ttt.Holdings'),
        ),
    ]
