# Generated by Django 2.1.7 on 2019-03-22 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0003_auto_20190322_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this transaction', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='holdings',
            name='ticker',
            field=models.CharField(help_text='Enter the ticker for this transaction', max_length=5),
        ),
    ]
