# Generated by Django 2.1.7 on 2019-03-23 05:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0004_auto_20190322_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this holding', primary_key=True, serialize=False)),
                ('ticker', models.CharField(help_text='Enter the ticker for this holding', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price for this holding', max_digits=11)),
                ('quantity', models.IntegerField(help_text='Enter the quantity for this holding', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='holdings',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Enter the amount of cash for this portfolio', max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this portfolio', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='league',
            field=models.ForeignKey(help_text='Select a league for this portfolio', on_delete=django.db.models.deletion.CASCADE, to='ttt.League'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='player',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Holdings',
        ),
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttt.Portfolio'),
        ),
    ]
