# Generated by Django 2.1.7 on 2019-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20181103_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
