# Generated by Django 2.1.7 on 2019-03-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190321_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransaction',
            name='timeInForce',
            field=models.ForeignKey(help_text='Select a time in force for this transaction', on_delete=django.db.models.deletion.CASCADE, to='trade.TimeInForce'),
        ),
        migrations.AlterField(
            model_name='timeinforce',
            name='name',
            field=models.CharField(help_text='Enter a time in force (e.g. Good-til-canceled)', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='timeInForce',
            field=models.ForeignKey(help_text='Select a time in force for this transaction', on_delete=django.db.models.deletion.CASCADE, to='trade.TimeInForce'),
        ),
    ]
