# Generated by Django 2.1.7 on 2019-03-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190321_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransaction',
            name='timeInForce',
            field=models.ForeignKey(help_text='Select a time in force for this transaction', on_delete=django.db.models.deletion.CASCADE, to='trade.TimeInForce'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='price1',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price for this transaction', max_digits=11),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='timeInForce',
            field=models.ForeignKey(help_text='Select a time in force for this transaction', on_delete=django.db.models.deletion.CASCADE, to='trade.TimeInForce'),
        ),
    ]
