# Generated by Django 2.1.7 on 2019-03-22 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0007_auto_20190321_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='admin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='league_admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(related_name='league_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='timeInForce',
            field=models.ForeignKey(help_text='Select a time in force for this transaction', on_delete=django.db.models.deletion.CASCADE, to='trade.TimeInForce'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='timeInForce',
            field=models.ForeignKey(help_text='Select a time in force for this transaction', on_delete=django.db.models.deletion.CASCADE, to='trade.TimeInForce'),
        ),
    ]
