# Generated by Django 2.1.7 on 2019-03-22 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20190322_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='league_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='timeInForce',
            field=models.ForeignKey(help_text='Select a time in force for this transaction', on_delete=django.db.models.deletion.CASCADE, to='trade.TimeInForce'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='timeInForce',
            field=models.ForeignKey(help_text='Select a time in force for this transaction', on_delete=django.db.models.deletion.CASCADE, to='trade.TimeInForce'),
        ),
    ]
